### ISSUE TITLE
Usage with PM2

### ISSUE THREAD

**Issue by bjrmatos** [pipedrive/kardia#15]
hi, good work! i'm exploring how to use this module with [PM2](https://github.com/Unitech/pm2), is it possible?

**Comment by martintajur** [comment]
Sorry for not having to respond any earlier. Stumbled upon PM2 and took a closer look (we haven't had any prior experience with PM2). It seems to offer a complete suite with additional compatible plugins for achieving similar status information fetching and aggregation to that of kardia. However, I think kardia does offer a more fine grain control over which (custom) metrics you like to track. There is no specific PM2 compatibility out of the box. If you can make it work, let us know but we have no plans to integrate it with PM2 on our own since our development is mostly driven by our needs (we're very open to open source collaborations though!)
